spring.application.name=tienda-kalza

spring.datasource.url=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.fahtquucwqvmhujxnzqi
spring.datasource.password=codigochiquitin.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=${JWT_SECRET:clave-secreta-muy-larga-para-firmar-tokens-jwt-segura-256-bits-minimo-32-chars}
jwt.expiration=86400000